# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: St Michael and All Angels
subtitle: Tonbridge Road, Maidstone, ME16 8JS
email: mark.elvers@tunbury.org
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
future: true

social:
  type: Organization
  name: St Michael and All Angels, Maidstone
  links:
    - http://www.facebook.com/pages/St-Michael-All-Angels-Church-Maidstone/341687052600534

footer:
  links:
    - label: Safeguarding Policy
      url: /safeguarding-policy
    - label: Privacy Policy
      url: /privacy-policy
    - label: A Church Near You
      url: https://www.achurchnearyou.com/church/12188/
    - label: Forward in Faith, Canterbury
      url: http://www.forwardinfaithcanterbury.org/

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "UA-122924278-1"
    anonymize_ip: false # default

# Build settings
permalink: /news/:path/
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
repository: mtelvers/stmichaels
plugins:
  - jekyll-feed
  - jekyll-include-cache

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

collections:
  wwi:
    output: true
  windows:

defaults:
  -
    scope:
      path: ""
    values:
      layout: "single"
      classes: "wide"
      toc: false
      show_date: true
      sidebar:
        nav: main
  -
    scope:
      path: "/about/*"
    values:
      sidebar:
        nav: about
  -
    scope:
      path: "/resources/*"
    values:
      sidebar:
        nav: resources
  -
    scope:
      type: "wwi"
    values:
      layout: "solider"
      sidebar:
        nav: wwi

